name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 9.x, 10.x, 11.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm test
    - run: npm run lint
    - run: npm run cs-check
      env:
        CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v2.1.0
      with:
        node-version: 13.x
    - run: npm install
    - run: npm run build
    - name: Deploy playground to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.0
      with:
        keep_history: true
        target-branch: gh-pages
        build_dir: packages/playground/build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  docs:
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.0.2
      with:
        python-version: 3.6
    - run: pip install -r requirements.docs.txt
    - run: mkdocs build --clean
